"""add work item url

Revision ID: 28361edf3e47
Revises: cc8c7ce3fb52
Create Date: 2026-10-03 21:57:39.085470

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28361edf3e47"
down_revision: str | Sequence[str] | None = "cc8c7ce3fb52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url", sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.drop_column("url")

    # ### end Alembic commands ###
