"""add work item assignee

Revision ID: 5b3beedabfc0
Revises: a9d3e1f4c2b7
Create Date: 2026-10-09 13:54:18.781374

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b3beedabfc0"
down_revision: str | Sequence[str] | None = "a9d3e1f4c2b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assignee", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.drop_column("assignee")

    # ### end Alembic commands ###
