"""add indexes to work_items team_id and project_id

Revision ID: 6183c646d3ed
Revises: d4dbe6431ee1
Create Date: 2026-07-09 13:15:28.135643

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6183c646d3ed'
down_revision: str | Sequence[str] | None = 'd4dbe6431ee1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_team_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_project_id'))

    # ### end Alembic commands ###
