"""add unique index on snapshot scope and day

Revision ID: a5104220b660
Revises: ef20b90c18df
Create Date: 2026-07-11 19:54:50.445688

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5104220b660'
down_revision: str | Sequence[str] | None = 'ef20b90c18df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_snapshots_team_id'))
        batch_op.create_index(
            'ix_forecast_snapshots_project_captured_on',
            ['project_id', 'captured_on'],
            unique=True,
        )
        batch_op.create_index(
            'ix_forecast_snapshots_team_captured_on',
            ['team_id', 'captured_on'],
            unique=True,
        )

    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_team_id'))
        batch_op.create_index(
            'ix_metric_snapshots_project_captured_on',
            ['project_id', 'captured_on'],
            unique=True,
        )
        batch_op.create_index(
            'ix_metric_snapshots_team_captured_on',
            ['team_id', 'captured_on'],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_snapshots_team_captured_on')
        batch_op.drop_index('ix_metric_snapshots_project_captured_on')
        batch_op.create_index(
            batch_op.f('ix_metric_snapshots_team_id'), ['team_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_metric_snapshots_project_id'), ['project_id'], unique=False
        )

    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_snapshots_team_captured_on')
        batch_op.drop_index('ix_forecast_snapshots_project_captured_on')
        batch_op.create_index(
            batch_op.f('ix_forecast_snapshots_team_id'), ['team_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_forecast_snapshots_project_id'), ['project_id'], unique=False
        )

    # ### end Alembic commands ###
