"""advice feedback and persona guidance

Revision ID: cc8c7ce3fb52
Revises: a5104220b660
Create Date: 2026-07-12 01:12:54.757459

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc8c7ce3fb52'
down_revision: str | Sequence[str] | None = 'a5104220b660'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('advice_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advice_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advice_feedback_persona'), ['persona'], unique=False)

    op.create_table('persona_guidance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persona_guidance', schema=None) as batch_op:
        batch_op.create_index(
            'ix_persona_guidance_persona_version', ['persona', 'version'], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona_guidance', schema=None) as batch_op:
        batch_op.drop_index('ix_persona_guidance_persona_version')

    op.drop_table('persona_guidance')
    with op.batch_alter_table('advice_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advice_feedback_persona'))

    op.drop_table('advice_feedback')
    # ### end Alembic commands ###
