"""create snapshot tables

Revision ID: ef20b90c18df
Revises: fd57d85b1b33
Create Date: 2026-07-11 19:23:48.644467

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef20b90c18df'
down_revision: str | Sequence[str] | None = 'fd57d85b1b33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('p50_days', sa.Integer(), nullable=True),
    sa.Column('p85_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_forecast_snapshots_project_id'), ['project_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_forecast_snapshots_team_id'), ['team_id'], unique=False
        )

    op.create_table('metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('wip', sa.Integer(), nullable=False),
    sa.Column('lead_time_p50_seconds', sa.Float(), nullable=True),
    sa.Column('lead_time_p85_seconds', sa.Float(), nullable=True),
    sa.Column('cycle_time_p50_seconds', sa.Float(), nullable=True),
    sa.Column('cycle_time_p85_seconds', sa.Float(), nullable=True),
    sa.Column('blocked_seconds', sa.Float(), nullable=False),
    sa.Column('flow_efficiency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_metric_snapshots_project_id'), ['project_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_metric_snapshots_team_id'), ['team_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_team_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_project_id'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_snapshots_team_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_snapshots_project_id'))

    op.drop_table('forecast_snapshots')
    # ### end Alembic commands ###
