"""make external_id indexes unique

Revision ID: fd57d85b1b33
Revises: 6183c646d3ed
Create Date: 2026-07-10 15:56:11.038575

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd57d85b1b33'
down_revision: str | Sequence[str] | None = '6183c646d3ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_external_id'))
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_external_id'))
        batch_op.create_index(batch_op.f('ix_projects_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_external_id'))
        batch_op.create_index(batch_op.f('ix_teams_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_external_id'))
        batch_op.create_index(
            batch_op.f('ix_work_items_external_id'), ['external_id'], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_external_id'))
        batch_op.create_index(
            batch_op.f('ix_work_items_external_id'), ['external_id'], unique=False
        )

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_external_id'))
        batch_op.create_index(batch_op.f('ix_teams_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_external_id'))
        batch_op.create_index(batch_op.f('ix_projects_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_external_id'))
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###
